// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact            = require("reason-react/lib/js/src/ReasonReact.js");
var ReactStepperHorizontal = require("react-stepper-horizontal");

function make(steps, activeStep, _) {
  return ReasonReact.wrapJsForReason(ReactStepperHorizontal.HorizontalStepper, {
              activeStep: activeStep,
              steps: steps
            }, /* array */[]);
}

exports.make = make;
/* ReasonReact Not a pure module */
