// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactStepperHorizontal = require("react-stepper-horizontal");

function make(
  steps,
  $staropt$star,
  $staropt$star$1,
  $staropt$star$2,
  $staropt$star$3,
  $staropt$star$4,
  $staropt$star$5,
  $staropt$star$6,
  $staropt$star$7,
  $staropt$star$8,
  $staropt$star$9,
  $staropt$star$10,
  $staropt$star$11,
  $staropt$star$12,
  $staropt$star$13,
  $staropt$star$14,
  $staropt$star$15,
  $staropt$star$16,
  $staropt$star$17,
  $staropt$star$18,
  $staropt$star$19,
  defaultBorderColor,
  completeBorderColor,
  activeBorderColor,
  $staropt$star$20,
  $staropt$star$21,
  $staropt$star$22,
  $staropt$star$23,
  $staropt$star$24,
  $staropt$star$25,
  $staropt$star$26,
  $staropt$star$27,
  titleStyle,
  circleStyle,
  $staropt$star$28,
  _
) {
  var activeStep = $staropt$star ? $staropt$star[0] : 0;
  var activeColor = $staropt$star$1 ? $staropt$star$1[0] : "#5096FF";
  var completeColor = $staropt$star$2 ? $staropt$star$2[0] : "#5096FF";
  var defaultColor = $staropt$star$3 ? $staropt$star$3[0] : "#E0E0E0";
  var activeTitleColor = $staropt$star$4 ? $staropt$star$4[0] : "#000";
  var completeTitleColor = $staropt$star$5 ? $staropt$star$5[0] : "#000";
  var defaultTitleColor = $staropt$star$6 ? $staropt$star$6[0] : "#757575";
  var circleFontColor = $staropt$star$7 ? $staropt$star$7[0] : "#FFF";
  var size = $staropt$star$8 ? $staropt$star$8[0] : 32;
  var circleFontSize = $staropt$star$9 ? $staropt$star$9[0] : 16;
  var titleFontSize = $staropt$star$10 ? $staropt$star$10[0] : 16;
  var circleTop = $staropt$star$11 ? $staropt$star$11[0] : 24;
  var titleTop = $staropt$star$12 ? $staropt$star$12[0] : 8;
  var defaultOpacity = $staropt$star$13 ? $staropt$star$13[0] : 1;
  var completeOpacity = $staropt$star$14 ? $staropt$star$14[0] : 1;
  var activeOpacity = $staropt$star$15 ? $staropt$star$15[0] : 1;
  var defaultTitleOpacity = $staropt$star$16 ? $staropt$star$16[0] : 1;
  var completeTitleOpacity = $staropt$star$17 ? $staropt$star$17[0] : 1;
  var activeTitleOpacity = $staropt$star$18 ? $staropt$star$18[0] : 1;
  var barStyle = $staropt$star$19 ? $staropt$star$19[0] : "solid";
  var defaultBorderStyle = $staropt$star$20 ? $staropt$star$20[0] : "solid";
  var completeBorderStyle = $staropt$star$21 ? $staropt$star$21[0] : "solid";
  var activeBorderStyle = $staropt$star$22 ? $staropt$star$22[0] : "solid";
  var defaultBarColor = $staropt$star$23 ? $staropt$star$23[0] : "#E0E0E0";
  var completeBarColor = $staropt$star$24 ? $staropt$star$24[0] : "#E0E0E0";
  var activeCircleFontColor = $staropt$star$25 ? $staropt$star$25[0] : "#000";
  var defaultCircleFontColor = $staropt$star$26 ? $staropt$star$26[0] : "#000";
  var checkIcon = $staropt$star$27 ? $staropt$star$27[0] : null;
  var barHeight = $staropt$star$28 ? $staropt$star$28[0] : 1;
  return ReasonReact.wrapJsForReason(
    ReactStepperHorizontal.default,
    {
      activeStep: activeStep,
      steps: steps,
      activeColor: activeColor,
      completeColor: completeColor,
      defaultColor: defaultColor,
      activeTitleColor: activeTitleColor,
      completeTitleColor: completeTitleColor,
      defaultTitleColor: defaultTitleColor,
      circleFontColor: circleFontColor,
      size: size,
      circleFontSize: circleFontSize,
      titleFontSize: titleFontSize,
      circleTop: circleTop,
      titleTop: titleTop,
      defaultOpacity: defaultOpacity,
      completeOpacity: completeOpacity,
      activeOpacity: activeOpacity,
      defaultTitleOpacity: defaultTitleOpacity,
      completeTitleOpacity: completeTitleOpacity,
      activeTitleOpacity: activeTitleOpacity,
      barStyle: barStyle,
      defaultBarColor: defaultBarColor,
      defaultBorderColor: defaultBorderColor,
      completeBorderColor: completeBorderColor,
      activeBorderColor: activeBorderColor,
      defaultBorderStyle: defaultBorderStyle,
      completeBorderStyle: completeBorderStyle,
      activeBorderStyle: activeBorderStyle,
      completeBarColor: completeBarColor,
      activeCircleFontColor: activeCircleFontColor,
      checkIcon: checkIcon,
      defaultCircleFontColor: defaultCircleFontColor,
      titleStyle: titleStyle,
      circleStyle: circleStyle,
      barHeight: barHeight
    },
    /* array */ []
  );
}

exports.make = make;
/* ReasonReact Not a pure module */
